# Generated by Django 2.0.3 on 2023-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180403_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Start'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.CharField(choices=[('1', 'Ongoing'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Start'), ('2', 'Working'), ('3', 'Done')], default=1, max_length=7),
        ),
    ]
